services:
  ndx-sandbox:
    build:
      context: .
    image: ${NDX_SANDBOX_IMAGE:-hika00/ndx-sandbox:0.1.0}
    working_dir: /workspace
    command: ["sleep", "infinity"]
    volumes:
      - ./docker/volume/workspace:/workspace
    stdin_open: true
    tty: true
